server:
  port: 8081
spring:
  application:
    name: stocker-data
eureka:
  instance:
    appname: stocker-data
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka
logging:
  level:
    org.springframework: ERROR
    com.stocker: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
