server:
  port: 8081
spring:
  application:
    name: stocker-data
eureka:
  client:
    register-with-eureka: true
  instance:
    appname: stocker-data
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework: ERROR
    com.stocker: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
