server:
  port: 8080
spring:
  application:
    name: stocker-data
eureka:
  instance:
    appname: stocker-data
    prefer-ip-address: true
    ip-address: 192.168.99.100
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka
logging:
  level:
    org:
      springframework: INFO
    com: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
stocker:
  mongodb:
    url: mongodb://192.168.99.100
  strategy:
    dividendAristocrats: DIVIDENDARISTOCRATS
