server:
  port: 8084
spring:
  application:
    name: weka-service
eureka:
  instance:
    appname: weka-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework: ERROR
    com.stocker: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
