version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Build started on `date`
      - export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain ruslanzdor --domain-owner 244092297712 --query authorizationToken --output text`
  build:
    commands:
      - mvn test
      - mvn package
      - aws s3 aws s3 cp stockerdata/target/stocker-data-1.0.jar s3://gram-deploy/stocker-data-1.0.jar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - stockerdata/buildspec.yml
    - stockerdata/template-mvn.yml
  discard-paths: yes
