version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Build started on `date`
      - export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain ruslanzdor --domain-owner 244092297712 --query authorizationToken --output text`
  build:
    commands:
      - mvn test
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  name: simplename
  files:
    - stockerdata/target/stocker-data-1.0.jar
    - stockerdata/appspec.yml
    - stockerdata/buildspec.yml
    - stockerdata/template-mvn.yml
  discard-paths: yes
  type: zip
