AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  LoadAllStockSymbols:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: load-all-stock-symbols
      CodeUri: s3://gram-deploy/stocker-data-1.0.jar
      Handler: com.stocker.data.controller.ScheduleStocksRequestHandler::handleRequest
      Runtime: java8
      Description: Get list of all available symbols
      MemorySize: 512
      Timeout: 10
      Role:
        Fn::GetAtt: StockerDataApplicationRole.Arn
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
  SaveCompany:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: save-company-information
      CodeUri: s3://gram-deploy/stocker-data-1.0.jar
      Handler: com.stocker.data.controller.SaveCompanyHandler::handleRequest
      Runtime: java8
      Description: Save company object to dynamoDB
      MemorySize: 512
      Timeout: 10
      Role:
        Fn::GetAtt: StockerDataApplicationRole.Arn
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
  YahooParser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: yahoo-stock-parser
      CodeUri: s3://gram-deploy/stocker-data-1.0.jar
      Handler: com.stocker.yahoo.parser.YahooParserHandler::handleRequest
      Runtime: java8
      Description: Get stock history data from Yahoo API
      MemorySize: 512
      Timeout: 10
      Role:
        Fn::GetAtt: StockerDataApplicationRole.Arn
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
  StockerDataApplicationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::244092297712:policy/stocker-data-dynamodb-policy
        - arn:aws:iam::244092297712:policy/stocker-data-step-functions
        - arn:aws:iam::244092297712:policy/service-role/AWSLambdaBasicExecutionRole-b8cef0c4-1121-440e-9f9f-cde9ea2fc412
  UpdateAllStocks:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: Update-All-Stocks-Yahoo
      DefinitionString:
        !Sub
          - |-
            {
              "StartAt": "Load stocks for update",
              "States": {
                "Load stocks for update": {
                  "Type": "Task",
                  "Resource": "${loadAllStocksArn}",
                  "Next": "Download All stocks"
                },
                "Download All stocks": {
                  "Type": "Map",
                  "InputPath": "$.stocks",
                  "MaxConcurrency": 0,
                  "Iterator": {
                    "StartAt": "Save Stock",
                    "States": {
                      "Yahoo Parser": {
                        "Type": "Task",
                        "Resource": "${yahooParser}",
                        "Next": "Save Stock"
                      },
                      "Save Stock": {
                        "Type": "Task",
                        "Resource": "${saveStock}",
                        "End": true
                      }
                    }
                  },
                  "End": true
                }
              }
            }
          - {
              loadAllStocksArn: !GetAtt [ LoadAllStockSymbols, Arn ],
              saveStock: !GetAtt [ SaveCompany, Arn ],
              yahooParser: !GetAtt [ YahooParser, Arn ]
            }
      RoleArn: arn:aws:iam::244092297712:role/service-role/StepFunctions-Update-All-Stocks-Yahoo-role-1e15a242
      Tags:
        - Key: "Name"
          Value: "Stocker"
