AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  LoadAllStockSymbols:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://gram-deploy/stocker-data-1.0.jar
      Handler: com.stocker.data.controller.ScheduleStocksRequestHandler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::244092297712:role/service-role/stocker-application-role-tmmxr7rw'
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AWSLambdaDynamoDBExecutionRole
      Tracing: Active
